name: Lighthouse

on:
  push:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Await CF Pages
        id: cfpages
        uses: WalshyDev/cf-pages-await@v1
        with:
          accountEmail: ${{ secrets.CF_ACCOUNT_EMAIL  }}
          apiKey: ${{ secrets.CF_API_KEY  }}
          accountId:  ${{ secrets.CF_ACCOUNT_ID}}
          project: 'moodsic'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Lighthouse CI Action
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: ${{ steps.cfpages.outputs.alias }}
          runs: 3
          configPath: '.github/workflows/lighthouserc-assertions.json'
          serverBaseUrl: https://lighthouse.thearc.dev
          serverToken: ${{ secrets.SERVER_TOKEN }}
          basicAuthUsername: ${{ secrets.LHCI_SERVER_BASIC_AUTH_USERNAME }}
          basicAuthPassword: ${{ secrets.LHCI_SERVER_BASIC_AUTH_PASSWORD }}
